"""init

Revision ID: 21ff60c88e9f
Revises: 0bd3729f0e15
Create Date: 2024-11-02 11:49:02.192920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '21ff60c88e9f'
down_revision: Union[str, None] = '0bd3729f0e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pins', 'media',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pins', 'media',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
