"""init

Revision ID: 3ded79e7fa21
Revises: 6fc710650401
Create Date: 2024-11-05 19:10:37.240442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3ded79e7fa21'
down_revision: Union[str, None] = '6fc710650401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('user_uid', sa.Uuid(), nullable=False),
    sa.Column('pin_uid', sa.Uuid(), nullable=True),
    sa.Column('comment_uid', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['comment_uid'], ['comments.uid'], ),
    sa.ForeignKeyConstraint(['pin_uid'], ['pins.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['user_accounts.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
