"""init

Revision ID: 5377174f8054
Revises: fde6e7d9302f
Create Date: 2024-11-03 13:49:59.973127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5377174f8054'
down_revision: Union[str, None] = 'fde6e7d9302f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_uid', sa.Uuid(), nullable=True))
    op.alter_column('comments', 'pin_uid',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'comments', 'comments', ['comment_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.alter_column('comments', 'pin_uid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('comments', 'comment_uid')
    # ### end Alembic commands ###
