"""init

Revision ID: ec2e6ae35c49
Revises: 34c9d8fd0ad3
Create Date: 2024-11-03 16:53:21.525164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec2e6ae35c49'
down_revision: Union[str, None] = '34c9d8fd0ad3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_uid', sa.Uuid(), nullable=True))
    op.drop_constraint('comments_comment_uid_fkey', 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'comments', ['parent_uid'], ['uid'])
    op.drop_column('comments', 'comment_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('comment_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key('comments_comment_uid_fkey', 'comments', 'comments', ['comment_uid'], ['uid'])
    op.drop_column('comments', 'parent_uid')
    # ### end Alembic commands ###
